namespace Dashboard.Migrations
{
    using Common;
    using Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Dashboard.Models.DashboardDBContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Dashboard.Models.DashboardDBContext context)
        {
            context.StudentTypes.AddOrUpdate
                (st => st.StudentTypeId,
                new StudentType { StudentTypeId = 1, Title = "Undergraduate - Freshman", Capacity = 100, Enrolled = 58 },
                new StudentType { StudentTypeId = 2, Title = "Undergraduate - Sophomore", Capacity = 100, Enrolled = 62 },
                new StudentType { StudentTypeId = 3, Title = "Undergraduate - Junior", Capacity = 100, Enrolled = 55 },
                new StudentType { StudentTypeId = 4, Title = "Undergraduate - Senior", Capacity = 100, Enrolled = 65 },
                new StudentType { StudentTypeId = 5, Title = "Graduate - Masters", Capacity = 50, Enrolled = 40 },
                new StudentType { StudentTypeId = 6, Title = "Graduate - PhD", Capacity = 50, Enrolled = 24 }
                );

            context.Students.AddOrUpdate
                (s => s.StudentId,
                new Student { StudentId = 1, StudentTypeId = 1, Name = "VERNON CARLOS", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 2, StudentTypeId = 1, Name = "MACK VICTOR", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 3, StudentTypeId = 1, Name = "LUKE RICHARD", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 4, StudentTypeId = 1, Name = "BRENT RALPH", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 5, StudentTypeId = 1, Name = "CARTER CHARLES", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 6, StudentTypeId = 1, Name = "MASON ANTONIO", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 7, StudentTypeId = 1, Name = "CARSON LUIS", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 8, StudentTypeId = 1, Name = "VINCENT HARRY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 9, StudentTypeId = 1, Name = "BLAKE NATHAN", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 10, StudentTypeId = 1, Name = "EVERETT GARY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 11, StudentTypeId = 1, Name = "VANCE SHERRY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 12, StudentTypeId = 1, Name = "RYAN RUBY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 13, StudentTypeId = 1, Name = "NICHOLAS ALFRED", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 14, StudentTypeId = 1, Name = "OLIVER ADAM", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 15, StudentTypeId = 1, Name = "CRUZ FLORENCE", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 16, StudentTypeId = 1, Name = "RICHARD JEAN", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 17, StudentTypeId = 1, Name = "GABRIEL JOSEPH", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 18, StudentTypeId = 1, Name = "KIRBY TROY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 19, StudentTypeId = 1, Name = "LEIGH JACK", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 20, StudentTypeId = 1, Name = "WADE BEVERLY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 21, StudentTypeId = 1, Name = "GRADY SAMUEL", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 22, StudentTypeId = 1, Name = "HAZEL MARVIN", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 23, StudentTypeId = 1, Name = "MILES JEFFERY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 24, StudentTypeId = 1, Name = "GUY LEROY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 25, StudentTypeId = 1, Name = "STUART JAY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 26, StudentTypeId = 1, Name = "SAM SHIRLEY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 27, StudentTypeId = 1, Name = "TODD HAZEL", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 28, StudentTypeId = 1, Name = "JAMES HOLLY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 29, StudentTypeId = 1, Name = "JOYCE TOM", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 30, StudentTypeId = 1, Name = "ASHLEY RAYMOND", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 31, StudentTypeId = 1, Name = "SYLVESTER PAUL", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 32, StudentTypeId = 1, Name = "SHIRLEY ARTHUR", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 33, StudentTypeId = 1, Name = "EDGAR ANTHONY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 34, StudentTypeId = 1, Name = "FRANCIS EARL", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 35, StudentTypeId = 1, Name = "DEAN SAM", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 36, StudentTypeId = 1, Name = "COLE JAMES", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 37, StudentTypeId = 1, Name = "CHASE LOUIS", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 38, StudentTypeId = 1, Name = "FLETCHER NICHOLAS", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 39, StudentTypeId = 1, Name = "GEORGE AARON", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 40, StudentTypeId = 1, Name = "MARSHALL BRENT", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 41, StudentTypeId = 1, Name = "BROCK RAMON", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 42, StudentTypeId = 1, Name = "VERA DANIEL", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 43, StudentTypeId = 1, Name = "DREW CALVIN", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 44, StudentTypeId = 1, Name = "KELLEY STACEY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 45, StudentTypeId = 1, Name = "JACK ANDRE", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 46, StudentTypeId = 1, Name = "SHERMAN DERRICK", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 47, StudentTypeId = 1, Name = "BOYD FRANCISCO", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 48, StudentTypeId = 1, Name = "MARION MARION", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 49, StudentTypeId = 1, Name = "HALEY ALBERT", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 50, StudentTypeId = 1, Name = "YOUNG BRANDON", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 51, StudentTypeId = 1, Name = "BOOKER JACOB", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 52, StudentTypeId = 1, Name = "CECIL ANGEL", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 53, StudentTypeId = 1, Name = "MANUEL LESLIE", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 54, StudentTypeId = 1, Name = "MITCHELL FRANK", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 55, StudentTypeId = 1, Name = "ROMAN JOYCE", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 56, StudentTypeId = 1, Name = "FORREST TRACY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Female" },
                new Student { StudentId = 57, StudentTypeId = 1, Name = "HARRISON WALTER", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" },
                new Student { StudentId = 58, StudentTypeId = 1, Name = "MIRANDA SHELLY", DOB = Utilities.GenerateRandomDOBForAge(18, 20), Gender = "Male" }
                );

            context.Students.AddOrUpdate
                (s => s.StudentId,
                new Student { StudentId = 59, StudentTypeId = 2, Name = "BURTON CECIL", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 60, StudentTypeId = 2, Name = "JULIAN KYLE", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 61, StudentTypeId = 2, Name = "SIMON ALLAN", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 62, StudentTypeId = 2, Name = "LEONARD EDGAR", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 63, StudentTypeId = 2, Name = "CHRISTIAN MELVIN", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 64, StudentTypeId = 2, Name = "LLOYD GEORGE", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 65, StudentTypeId = 2, Name = "OWEN ASHLEY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 66, StudentTypeId = 2, Name = "LINDSEY BENJAMIN", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 67, StudentTypeId = 2, Name = "FELIX JOY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 68, StudentTypeId = 2, Name = "JACOB MANUEL", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 69, StudentTypeId = 2, Name = "KAY PENNY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 70, StudentTypeId = 2, Name = "SCOTT MARCUS", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 71, StudentTypeId = 2, Name = "DANIEL STACY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 72, StudentTypeId = 2, Name = "IRVING COREY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 73, StudentTypeId = 2, Name = "RAY GRACE", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 74, StudentTypeId = 2, Name = "BRUCE NEIL", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 75, StudentTypeId = 2, Name = "ARCHIE FLORA", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 76, StudentTypeId = 2, Name = "ANGEL PATRICK", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 77, StudentTypeId = 2, Name = "HENRY CHRISTY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 78, StudentTypeId = 2, Name = "SHANNON DALE", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 79, StudentTypeId = 2, Name = "VAUGHN CLIFFORD", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 80, StudentTypeId = 2, Name = "PAIGE KEITH", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 81, StudentTypeId = 2, Name = "TERRELL FREDRICK", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 82, StudentTypeId = 2, Name = "MARCUS VERA", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 83, StudentTypeId = 2, Name = "FRANKLIN VERNON", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 84, StudentTypeId = 2, Name = "BRANDON HERBERT", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 85, StudentTypeId = 2, Name = "ANDRES ANGELO", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 86, StudentTypeId = 2, Name = "WILLARD GERARD", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 87, StudentTypeId = 2, Name = "MAYNARD HOMER", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 88, StudentTypeId = 2, Name = "CARROLL JULIAN", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 89, StudentTypeId = 2, Name = "ROSA ROSA", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 90, StudentTypeId = 2, Name = "CRAIG DENNIS", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 91, StudentTypeId = 2, Name = "COURTNEY CHESTER", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 92, StudentTypeId = 2, Name = "ROSARIO HUBERT", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 93, StudentTypeId = 2, Name = "JOY WESLEY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 94, StudentTypeId = 2, Name = "GILBERT LANCE", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 95, StudentTypeId = 2, Name = "BRADFORD SHANNON", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 96, StudentTypeId = 2, Name = "LANCE ALFONSO", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 97, StudentTypeId = 2, Name = "KIRK LYNN", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 98, StudentTypeId = 2, Name = "DENNIS ANDRES", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 99, StudentTypeId = 2, Name = "PAUL BRUCE", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 100, StudentTypeId = 2, Name = "ERVIN DAMON", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 101, StudentTypeId = 2, Name = "COREY RODERICK", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 102, StudentTypeId = 2, Name = "KEITH TRAVIS", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 103, StudentTypeId = 2, Name = "TYLER GREGORY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 104, StudentTypeId = 2, Name = "HERBERT ARCHIE", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 105, StudentTypeId = 2, Name = "AMOS ROY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 106, StudentTypeId = 2, Name = "LEE FREDERICK", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 107, StudentTypeId = 2, Name = "WILSON COURTNEY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 108, StudentTypeId = 2, Name = "CHESTER OTIS", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 109, StudentTypeId = 2, Name = "BENJAMIN SHELLEY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 110, StudentTypeId = 2, Name = "SAMUEL TERRY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 111, StudentTypeId = 2, Name = "JEWELL GABRIEL", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 112, StudentTypeId = 2, Name = "CLARK ORLANDO", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 113, StudentTypeId = 2, Name = "ISAAC CLINTON", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 114, StudentTypeId = 2, Name = "LORENZO BARRY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 115, StudentTypeId = 2, Name = "NATHAN KAY", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 116, StudentTypeId = 2, Name = "JEAN LEIGH", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 117, StudentTypeId = 2, Name = "NOEL LORENZO", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 118, StudentTypeId = 2, Name = "TOM MALCOLM", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" },
                new Student { StudentId = 119, StudentTypeId = 2, Name = "STEWART ROLAND", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Male" },
                new Student { StudentId = 120, StudentTypeId = 2, Name = "FLOYD WILBUR", DOB = Utilities.GenerateRandomDOBForAge(19, 21), Gender = "Female" }
                );

            context.Students.AddOrUpdate
                (s => s.StudentId,
                new Student { StudentId = 121, StudentTypeId = 3, Name = "LARA DOUGLAS", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 122, StudentTypeId = 3, Name = "WILLIS LUTHER", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 123, StudentTypeId = 3, Name = "ARTHUR BERNARD", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 124, StudentTypeId = 3, Name = "SANTOS GLENN", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 125, StudentTypeId = 3, Name = "KENT VINCENT", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 126, StudentTypeId = 3, Name = "WILEY CODY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 127, StudentTypeId = 3, Name = "PENNY MILTON", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 128, StudentTypeId = 3, Name = "ALLISON BRYAN", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 129, StudentTypeId = 3, Name = "RALPH ISAAC", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 130, StudentTypeId = 3, Name = "AARON SHELBY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 131, StudentTypeId = 3, Name = "JAY TODD", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 132, StudentTypeId = 3, Name = "WALLACE LUKE", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 133, StudentTypeId = 3, Name = "NORMAN FRANCIS", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 134, StudentTypeId = 3, Name = "RANDOLPH RYAN", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 135, StudentTypeId = 3, Name = "BRYAN NORMAN", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 136, StudentTypeId = 3, Name = "KYLE RANDALL", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 137, StudentTypeId = 3, Name = "SANTIAGO LEON", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 138, StudentTypeId = 3, Name = "RUSSELL LYLE", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 139, StudentTypeId = 3, Name = "DUDLEY HERMAN", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 140, StudentTypeId = 3, Name = "ALFONSO WILLARD", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 141, StudentTypeId = 3, Name = "CLIFTON KENNY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 142, StudentTypeId = 3, Name = "ELLIS LINDSAY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 143, StudentTypeId = 3, Name = "GREGORY LEONARD", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 144, StudentTypeId = 3, Name = "HERMAN LAWRENCE", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 145, StudentTypeId = 3, Name = "ROY CRAIG", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 146, StudentTypeId = 3, Name = "MURRAY HENRY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 147, StudentTypeId = 3, Name = "GAY CHRISTIE", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 148, StudentTypeId = 3, Name = "RANDALL HOPE", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 149, StudentTypeId = 3, Name = "ROLAND HANNAH", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 150, StudentTypeId = 3, Name = "MONROE ROSE", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 151, StudentTypeId = 3, Name = "CLIFFORD FELIX", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 152, StudentTypeId = 3, Name = "SHELLEY LLOYD", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 153, StudentTypeId = 3, Name = "MAY CLIFTON", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 154, StudentTypeId = 3, Name = "WARD LESTER", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 155, StudentTypeId = 3, Name = "GRANT KIM", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 156, StudentTypeId = 3, Name = "RUDOLPH CURTIS", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 157, StudentTypeId = 3, Name = "FRANCISCO ABRAHAM", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 158, StudentTypeId = 3, Name = "SHERRY RUDOLPH", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 159, StudentTypeId = 3, Name = "HOLLY THOMAS", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 160, StudentTypeId = 3, Name = "STACEY GUY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 161, StudentTypeId = 3, Name = "RODERICK STANLEY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 162, StudentTypeId = 3, Name = "FREDERICK ALLISON", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 163, StudentTypeId = 3, Name = "CASEY FLOYD", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 164, StudentTypeId = 3, Name = "NEIL CARLTON", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 165, StudentTypeId = 3, Name = "TROY MEREDITH", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 166, StudentTypeId = 3, Name = "CODY SYLVESTER", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 167, StudentTypeId = 3, Name = "HOPE IRVING", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 168, StudentTypeId = 3, Name = "SHELTON CHRISTIAN", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 169, StudentTypeId = 3, Name = "CHRISTIE CASEY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 170, StudentTypeId = 3, Name = "GREGG WHITNEY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 171, StudentTypeId = 3, Name = "KIM EVERETT", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 172, StudentTypeId = 3, Name = "ANTONIO TYLER", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 173, StudentTypeId = 3, Name = "ROSE KELLY", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Male" },
                new Student { StudentId = 174, StudentTypeId = 3, Name = "EARL STUART", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" },
                new Student { StudentId = 175, StudentTypeId = 3, Name = "HANNAH NOEL", DOB = Utilities.GenerateRandomDOBForAge(20, 22), Gender = "Female" }
                );

            context.Students.AddOrUpdate
                (s => s.StudentId,
                new Student { StudentId = 176, StudentTypeId = 4, Name = "AUSTIN SCOTT", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 177, StudentTypeId = 4, Name = "HESTER BRADLEY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 178, StudentTypeId = 4, Name = "TAYLOR KENT", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 179, StudentTypeId = 4, Name = "HARRY RAY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 180, StudentTypeId = 4, Name = "BRADY DREW", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 181, StudentTypeId = 4, Name = "CLAY JEWELL", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 182, StudentTypeId = 4, Name = "DALE FORREST", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 183, StudentTypeId = 4, Name = "WHITNEY GREGG", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 184, StudentTypeId = 4, Name = "SHELBY RUSSELL", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 185, StudentTypeId = 4, Name = "LANE LINDSEY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 186, StudentTypeId = 4, Name = "CHARLES CLAYTON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 187, StudentTypeId = 4, Name = "LESTER DEAN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 188, StudentTypeId = 4, Name = "AVERY KIRK", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 189, StudentTypeId = 4, Name = "CAREY AMOS", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 190, StudentTypeId = 4, Name = "DOUGLAS ERVIN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 191, StudentTypeId = 4, Name = "CALVIN HOWARD", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 192, StudentTypeId = 4, Name = "DAMON ", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 193, StudentTypeId = 4, Name = "ARNOLD CAMERON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 194, StudentTypeId = 4, Name = "ANDRE GILBERT", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 195, StudentTypeId = 4, Name = "ANGELO GRADY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 196, StudentTypeId = 4, Name = "ELLIOTT PAIGE", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 197, StudentTypeId = 4, Name = "WESLEY WINSTON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 198, StudentTypeId = 4, Name = "KENNY ", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 199, StudentTypeId = 4, Name = "WINSTON PRESTON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 200, StudentTypeId = 4, Name = "STANLEY RANDOLPH", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 201, StudentTypeId = 4, Name = "SOLOMON KENDALL", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 202, StudentTypeId = 4, Name = "ALLAN ROSARIO", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 203, StudentTypeId = 4, Name = "LYNN CONRAD", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 204, StudentTypeId = 4, Name = "REED WARREN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 205, StudentTypeId = 4, Name = "FLORA ALEXANDER", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 206, StudentTypeId = 4, Name = "MELVIN GORDON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 207, StudentTypeId = 4, Name = "THOMAS MIRANDA", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 208, StudentTypeId = 4, Name = "DALTON HARVEY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 209, StudentTypeId = 4, Name = "GERARD FRANKLIN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 210, StudentTypeId = 4, Name = "LOGAN TERRELL", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 211, StudentTypeId = 4, Name = "STACY CLEVELAND", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 212, StudentTypeId = 4, Name = "CHERRY BLAKE", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 213, StudentTypeId = 4, Name = "CARLTON ARNOLD", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 214, StudentTypeId = 4, Name = "BLAIR CAREY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 215, StudentTypeId = 4, Name = "ALFRED MOSES", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 216, StudentTypeId = 4, Name = "MAXWELL WADE", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 217, StudentTypeId = 4, Name = "BRYANT SHERMAN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 218, StudentTypeId = 4, Name = "GORDON TYSON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 219, StudentTypeId = 4, Name = "WARREN LARA", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 220, StudentTypeId = 4, Name = "NORRIS OWEN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 221, StudentTypeId = 4, Name = "HEATH BRADFORD", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 222, StudentTypeId = 4, Name = "LESLIE SIMON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 223, StudentTypeId = 4, Name = "MORGAN NEAL", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 224, StudentTypeId = 4, Name = "GARY LEE", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 225, StudentTypeId = 4, Name = "SANFORD CLAY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 226, StudentTypeId = 4, Name = "TRACY ROMAN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 227, StudentTypeId = 4, Name = "LUTHER AVERY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 228, StudentTypeId = 4, Name = "KENDALL GAY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 229, StudentTypeId = 4, Name = "HOUSTON JORDAN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 230, StudentTypeId = 4, Name = "ALLEN AUSTIN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 231, StudentTypeId = 4, Name = "CHRISTY ALLEN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 232, StudentTypeId = 4, Name = "RILEY HALEY", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 233, StudentTypeId = 4, Name = "BEVERLY NOLAN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 234, StudentTypeId = 4, Name = "ROSS SOLOMON", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 235, StudentTypeId = 4, Name = "BARRY HEATH", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 236, StudentTypeId = 4, Name = "ORLANDO LUCAS", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 237, StudentTypeId = 4, Name = "BENNETT OLIVER", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Male" },
                new Student { StudentId = 238, StudentTypeId = 4, Name = "LUCAS MACK", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 239, StudentTypeId = 4, Name = "WILBUR DOYLE", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" },
                new Student { StudentId = 240, StudentTypeId = 4, Name = "LYLE MARTIN", DOB = Utilities.GenerateRandomDOBForAge(21, 23), Gender = "Female" }
                );

            context.Students.AddOrUpdate
                (s => s.StudentId,
                new Student { StudentId = 241, StudentTypeId = 5, Name = "PERRY CHASE", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 242, StudentTypeId = 5, Name = "HUBERT SANTOS", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 243, StudentTypeId = 5, Name = "LUIS MAY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 244, StudentTypeId = 5, Name = "DOYLE VANCE", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 245, StudentTypeId = 5, Name = "CLINTON LOGAN", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 246, StudentTypeId = 5, Name = "LEON WALLACE", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 247, StudentTypeId = 5, Name = "ANTHONY MARSHALL", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 248, StudentTypeId = 5, Name = "NELSON KELLEY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 249, StudentTypeId = 5, Name = "BERNARD CHERRY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 250, StudentTypeId = 5, Name = "OTIS GARRETT", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 251, StudentTypeId = 5, Name = "PATRICK HESTER", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 252, StudentTypeId = 5, Name = "ABRAHAM SANFORD", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 253, StudentTypeId = 5, Name = "CLAYTON WILLIS", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 254, StudentTypeId = 5, Name = "CARLOS SANTIAGO", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 255, StudentTypeId = 5, Name = "CURTIS DUDLEY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 256, StudentTypeId = 5, Name = "FREDRICK CARROLL", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 257, StudentTypeId = 5, Name = "JEFFERY GRANT", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 258, StudentTypeId = 5, Name = "NEAL WILEY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 259, StudentTypeId = 5, Name = "LEWIS BRADY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 260, StudentTypeId = 5, Name = "LAWRENCE MAYNARD", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 261, StudentTypeId = 5, Name = "WALTER PERRY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 262, StudentTypeId = 5, Name = "JOSEPH KIRBY", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 263, StudentTypeId = 5, Name = "FRANK ROSS", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 264, StudentTypeId = 5, Name = "VICTOR BOOKER", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 265, StudentTypeId = 5, Name = "PRESTON DALTON", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 266, StudentTypeId = 5, Name = "LOUIS SPENCER", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 267, StudentTypeId = 5, Name = "SPENCER MILES", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 268, StudentTypeId = 5, Name = "CLEVELAND BLAIR", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 269, StudentTypeId = 5, Name = "KELLY MITCHELL", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 270, StudentTypeId = 5, Name = "SHELLY MONROE", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 271, StudentTypeId = 5, Name = "JEFFERSON LEWIS", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 272, StudentTypeId = 5, Name = "MARVIN CARSON", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 273, StudentTypeId = 5, Name = "HOMER MORRIS", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 274, StudentTypeId = 5, Name = "CAMERON BROCK", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 275, StudentTypeId = 5, Name = "LEROY JEFFERSON", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 276, StudentTypeId = 5, Name = "MEREDITH HOUSTON", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 277, StudentTypeId = 5, Name = "FLORENCE NELSON", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" },
                new Student { StudentId = 278, StudentTypeId = 5, Name = "MALCOLM MAXWELL", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 279, StudentTypeId = 5, Name = "GRACE MORGAN", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Male" },
                new Student { StudentId = 280, StudentTypeId = 5, Name = "GRAHAM NORRIS", DOB = Utilities.GenerateRandomDOBForAge(23, 28), Gender = "Female" }
                );

            context.Students.AddOrUpdate
                (s => s.StudentId,
                new Student { StudentId = 281, StudentTypeId = 6, Name = "MARTIN ELLIS", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 282, StudentTypeId = 6, Name = "RAMON VAUGHN", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 283, StudentTypeId = 6, Name = "GARRETT BURTON", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 284, StudentTypeId = 6, Name = "GLENN BRYANT", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 285, StudentTypeId = 6, Name = "HOWARD BOYD", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 286, StudentTypeId = 6, Name = "ADAM FLETCHER", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 287, StudentTypeId = 6, Name = "CONRAD ELLIOTT", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 288, StudentTypeId = 6, Name = "LINDSAY SHELTON", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 289, StudentTypeId = 6, Name = "ALBERT LANE", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 290, StudentTypeId = 6, Name = "JORDAN MURRAY", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 291, StudentTypeId = 6, Name = "ALEXANDER CRUZ", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 292, StudentTypeId = 6, Name = "TRAVIS MASON", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 293, StudentTypeId = 6, Name = "MILTON RILEY", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 294, StudentTypeId = 6, Name = "BRADLEY HARRISON", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 295, StudentTypeId = 6, Name = "RAYMOND GRAHAM", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 296, StudentTypeId = 6, Name = "MOSES STEWART", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 297, StudentTypeId = 6, Name = "HARVEY HUNTER", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 298, StudentTypeId = 6, Name = "HUNTER COLE", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 299, StudentTypeId = 6, Name = "TYSON TAYLOR", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 300, StudentTypeId = 6, Name = "RUBY CLARK", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 301, StudentTypeId = 6, Name = "MORRIS BENNETT", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 302, StudentTypeId = 6, Name = "DERRICK YOUNG", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" },
                new Student { StudentId = 303, StudentTypeId = 6, Name = "NOLAN WARD", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Male" },
                new Student { StudentId = 304, StudentTypeId = 6, Name = "TERRY WILSON", DOB = Utilities.GenerateRandomDOBForAge(24, 31), Gender = "Female" }
                );
        }
    }
}